# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - chickenapp

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mychickenapp.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_6b5c2af2cbdc4105a568ee19cd8e8d7f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_e1cb97b8cddd4456a2149c402a462c48 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mychickenapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6b5c2af2cbdc4105a568ee19cd8e8d7f }}/chicken:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'chickenapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1f9830718ad247a2b7daa54585cdb13a }}
        images: 'mychickenapp.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_6b5c2af2cbdc4105a568ee19cd8e8d7f }}/chicken:${{ github.sha }}'
    
    - name: Clean previous images, containers and volumes
      run: docker system prune -af

